behaviors:
  Opponent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 3.0e-4
    network_settings:
      num_layers: 2
      hidden_units: 128
    reward_signals:
      extrinsic:
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
