behaviors:
  Opponent:
    trainer_type: ppo

    # ───── Hyperparameters ──────────────
    hyperparameters:
      batch_size: 1024
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear

    # ───── Network Settings ─────────────
    network_settings:
      normalize: false
      num_layers: 2
      hidden_units: 128
      vis_encode_type: simple
      memory: null

    # ───── Reward Signals ──────────────
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

    # ───── Training & Logging ───────────
    max_steps: 2000000        # total steps to train
    time_horizon: 128         # how many steps to look ahead for rewards
    summary_freq: 1000        # log scalars every 1k steps
    checkpoint_interval: 50000  # write an ONNX checkpoint every 50k steps
