behaviors:
  Opponent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
    network_settings:
      num_layers: 2
      hidden_units: 128
      normalize: false
    reward_signals:
      extrinsic:
        strength: 1.0
    max_steps: 2000000        # total training steps
    time_horizon: 128         # for delayed punch rewards
    summary_freq: 5000
